### ISSUE TITLE
GCC requirement

### ISSUE THREAD

**Issue by biocyberman** [breuner/elfindo#1]
It's worth to mention in the README that gcc version 8+ should be used, otherwise `include <filesystem>` doesn't work.

**Comment by breuner** [comment]
Thanks @biocyberman !

I've added this to the README file now and thus will close this issue as completed.

Also, based on our other discussion, the current elbencho master branch just got a new new option `--copyto PATH`. It does a basic parallel file copy of disovered files to the given destination directory. An example could look like this:
```
elfindo --copyto /data/new/ /data/old/
```
This would copy everything found under the `/data/old/` dir to the `/data/new/` dir.
I didn't have time yet to experiment much with the speed and it also doesn't copy access permissions and such (so probably something like `rsync --size-only` is needed afterwards to set the access permissions), but at least wanted to let you know that this exists now.
